#!/bin/sh
rm -f intermine.log

echo ""
echo "##########################################################################################################################################"
echo "##########################################################################################################################################"
echo "#################################################### CHICKPEAMINE INTEGRATE ##############################################################"
echo "##########################################################################################################################################"
echo "##########################################################################################################################################"
echo ""

## ontologies
# ./gradlew integrate -Psource=go --stacktrace
# ./gradlew integrate -Psource=so --stacktrace
# ./gradlew integrate -Psource=plant-ontology --stacktrace
# ./gradlew integrate -Psource=plant-trait-ontology --stacktrace
# ./gradlew integrate -Psource=chickpea-crop-ontology --stacktrace

## InterPro
# ./gradlew integrate -Psource=interpro --stacktrace
# ./gradlew integrate -Psource=interpro-go --stacktrace

## LIS gene families
# ./gradlew integrate --stacktrace -Psource=legume.genefam.fam1.M65K
# ./gradlew integrate --stacktrace -Psource=legume.genefam.fam1.M65K.trees_ML_rooted

## cicar
# ./gradlew integrate --stacktrace -Psource=cicar-about

## CDCFrontier.gnm1
# ./gradlew integrate --stacktrace -Psource=CDCFrontier.gnm1.GkHc
# ./gradlew integrate --stacktrace -Psource=CDCFrontier.gnm1.ann1.nRhs.cds
# ./gradlew integrate --stacktrace -Psource=CDCFrontier.gnm1.ann1.nRhs.protein
# ./gradlew integrate --stacktrace -Psource=CDCFrontier.gnm1.ann1.nRhs.transcript
./gradlew integrate --stacktrace -Psource=CDCFrontier.gnm1.ann1.nRhs.gene_models_main
# ./gradlew integrate --stacktrace -Psource=CDCFrontier.gnm1.ann1.nRhs.legfed_v1_0.M65K.gfa
# ./gradlew integrate --stacktrace -Psource=CDCFrontier.gnm1.ann1.nRhs.pathway
# ./gradlew integrate --stacktrace -Psource=CDCFrontier.gnm1.ann1.syn.7Bqh
# ./gradlew integrate --stacktrace -Psource=CDCFrontier.gnm1.mrk.Varshney_Thudi_2019

## ICC4958.gnm2
# ./gradlew integrate --stacktrace -Psource=ICC4958.gnm2.bg5m
# ./gradlew integrate --stacktrace -Psource=ICC4958.gnm2.ann1.LCVX.cds
# ./gradlew integrate --stacktrace -Psource=ICC4958.gnm2.ann1.LCVX.protein
# ./gradlew integrate --stacktrace -Psource=ICC4958.gnm2.ann1.LCVX.transcript
# ./gradlew integrate --stacktrace -Psource=ICC4958.gnm2.ann1.LCVX.gene_models_main
# ./gradlew integrate --stacktrace -Psource=ICC4958.gnm2.ann1.LCVX.legfed_v1_0.M65K.gfa
### NEED TO BUILD PATHWAYS
### ./gradlew integrate --stacktrace -Psource=ICC4958.gnm2.ann1.LCVX.legfed_v1_0.M65K.pathway
# ./gradlew integrate --stacktrace -Psource=ICC4958.gnm2.ann1.syn.PdvJ
# ./gradlew integrate --stacktrace -Psource=ICC4958.gnm2.ann1.expr.4Y7B

## mixed
# ./gradlew integrate --stacktrace -Psource=mixed.gwas.Li_Ruperao_2018
# ./gradlew integrate --stacktrace -Psource=mixed.gwas.Varshney_Thudi_2019
