#!/bin/sh
rm -f intermine.log

## echo a big marker so we can see when this run started in the scroll
echo ""
echo "##################################################################################################"
echo "##################################################################################################"
echo "###################################### integrate #################################################"
echo "##################################################################################################"
echo "##################################################################################################"
echo ""

## ontologies and InterPro
./gradlew integrate -Psource=go --stacktrace
./gradlew integrate -Psource=so --stacktrace
./gradlew integrate -Psource=plant-ontology --stacktrace
./gradlew integrate -Psource=plant-trait-ontology --stacktrace
./gradlew integrate -Psource=interpro --stacktrace
./gradlew integrate -Psource=interpro-go --stacktrace

## LIS gene families
./gradlew integrate -Psource=lis.fam1-genefamily --stacktrace

###########
## cicar ##
###########

./gradlew integrate -Psource=cicar-about --stacktrace

## cicar.CDCFrontier.gnm1
./gradlew integrate -Psource=cicar.CDCFrontier.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=cicar.CDCFrontier.gnm1.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=cicar.CDCFrontier.gnm1.ann1-gff --stacktrace
./gradlew integrate -Psource=cicar.CDCFrontier.gnm1.ann1-protein-fasta --stacktrace
./gradlew integrate -Psource=cicar.CDCFrontier.gnm1.ann1.syn1-synteny --stacktrace

## cicar.ICC4958.gnm2
./gradlew integrate -Psource=cicar.ICC4958.gnm2-chromosome-fasta --stacktrace
./gradlew integrate -Psource=cicar.ICC4958.gnm2.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=cicar.ICC4958.gnm2.ann1-gff --stacktrace
./gradlew integrate -Psource=cicar.ICC4958.gnm2.ann1-protein-fasta --stacktrace
./gradlew integrate -Psource=cicar.ICC4958.gnm2.ann1.syn1-synteny --stacktrace
./gradlew integrate -Psource=cicar.ICC4958.gnm2.ann1-expression --stacktrace
