#!/bin/sh
echo "********** chickpeamine/postprocess **********"
ant clean

# the whole kaboodle kit
#ant -v

# create the parent ontology annotations
ant -v -Daction=create-ontology-parent-annotations

# run the index creation post-processors
ant -v -Daction=create-attribute-indexes
ant -v -Daction=summarise-objectstore
ant -v -Daction=create-autocomplete-index
ant -v -Daction=create-search-index
