#!/bin/sh
echo "********** chickpeamine/integrate **********"
ant clean

#ant -v -Dsource=so,go,to,po

#pg_restore -d chickpeamine /home/shokin/dumps/chickpeamine.ontologies.dat

#ant -v -Dsource=chado-genomics
#ant -v -Dsource=chado-genetics
#ant -v -Dsource=chado-featureprop
#ant -v -Dsource=chado-genefamilies
#ant -v -Dsource=chado-homology
#ant -v -Dsource=chado-reactome-file

#pg_restore -d chickpeamine /home/shokin/dumps/chickpeamine.chado.dat

#psql chickpeamine -f ../dbmodel/build/model/add-update-triggers.sql
#psql chickpeamine -f ../sql/cleanup-chado-bugs.sql
#psql chickpeamine -f ../sql/update-organisms.sql
#psql chickpeamine -f ../sql/update-identifiers.sql
#psql chickpeamine -f ../dbmodel/build/model/remove-update-triggers.sql

# load some expression
ant -v -Dsource=chickpea-expression
