#!/bin/sh
echo "********** chickpeamine/integrate **********"
ant clean

#pg_restore -d chickpeamine /home/analysis/shokin/dumps/chickpeamine.so-go.dat
#ant -v -Dsource=so,go
#pg_dump -Fc chickpeamine > /home/analysis/shokin/dumps/chickpeamine.so-go.dat

#pg_restore -d chickpeamine /home/analysis/shokin/dumps/chickpeamine.chado.dat
#ant -v -Dsource=chado-genomics,chado-go,chado-featureprop,chado-genefamilies,chado-homology,chado-reactome-file
#pg_dump -Fc chickpeamine > /home/analysis/shokin/dumps/chickpeamine.chado.dat

#psql chickpeamine -f ../dbmodel/build/model/add-update-triggers.sql
#psql chickpeamine -f ../sql/update-organisms.sql
#psql chickpeamine -f ../sql/update-identifiers.sql
#psql chickpeamine -f ../dbmodel/build/model/remove-update-triggers.sql

# load some expression
#ant -v -Dsource=chickpea-expression
